### ISSUE TITLE
Write tests for and document Service Book class

### ISSUE THREAD

**Issue by stephendonner** [mozilla/fxtest-jenkins-pipeline#24]
We need to write/improve docs and tests for the code in https://github.com/mozilla/fxtest-jenkins-pipeline/pull/23 which will hopefully make it into our shared library in some form or fashion.

Particularly perhaps, for starters, ```testProject('project name')```?

More specifics as we iterate on this, together!

**Comment by tarekziade** [comment]
relevant https://github.com/mozilla/fxtest-jenkins-pipeline/pull/31
