### ISSUE TITLE
Evaluate using the HTTP Request Plugin to reduce and simplify HTTP GET/POST calls to Service Book API

### ISSUE THREAD

**Issue by stephendonner** [mozilla/fxtest-jenkins-pipeline#25]
Soon after https://github.com/mozilla/fxtest-jenkins-pipeline/pull/23 lands, we should evaluate the HTTP Request Plugin[0][1][2], with the aim of greatly reducing and simplifying the HTTP GET/POST calls to the Service Book API, to get project repos, etc.

/cc @tarekziade @davehunt 

[0] https://github.com/jenkinsci/http-request-plugin
[1] https://wiki.jenkins.io/display/JENKINS/HTTP+Request+Plugin
[2] https://plugins.jenkins.io/http_request

**Comment by stephendonner** [comment]
@tarekziade would you mind taking a crack at this?

**Comment by davehunt** [comment]
Note that we'll need the plugin installed before we can merge/release this change. Maybe we could install the plugin on dev?

**Comment by stephendonner** [comment]
@davehunt sure; I've now installed version 1.8.20 on https://fx-test-jenkins-dev.stage.mozaws.net:8443/

**Comment by tarekziade** [comment]
@stephendonner sure yeah - thanks for installing it

**Comment by stephendonner** [comment]
Fixed by https://github.com/mozilla/fxtest-jenkins-pipeline/pull/31 right @tarekziade?

**Comment by davehunt** [comment]
Yep, this is done.
