### ISSUE TITLE
Servicebook: case insensitive lookups

### ISSUE THREAD

**Issue by tarekziade** [mozilla/fxtest-jenkins-pipeline#27]
once https://github.com/mozilla/fxtest-jenkins-pipeline/pull/23 is pushed
we should change the loop that looks for a project so it's case insensitive (e.g. Kinto vs kinto vs KINTO)

**Comment by rpappalax** [comment]
thanks, @tarekziade !

**Comment by stephendonner** [comment]
I _think_ I've fixed it with this commit in my PR: https://github.com/mozilla/fxtest-jenkins-pipeline/pull/23/commits/145f174022591dcf38a6c519ba12ffba79ecf479

I passed in "Kinto" via https://github.com/Kinto/kinto-integration-tests/pull/35/commits/85cd2506263c328c15e2fe8ac8731bd782b7c0b6 and it found the project from Service Book, as you can see from https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/kinto.stage.stephend/20/ (showing both commits of temporary casing change to pass "Kinto" to newly-created toLowerCase() code), and https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/kinto.stage.stephend/20/console

Console output: https://gist.github.com/stephendonner/52b52d6a14c3d4bd1896877d15300461

**Comment by rpappalax** [comment]
thank you, @stephendonner
