### ISSUE TITLE
v1.8 fails to get the project repo from Service Book's API, and is returned a 404, instead

### ISSUE THREAD

**Issue by stephendonner** [mozilla/fxtest-jenkins-pipeline#34]
![10aa90c7fab8fafd82abfeefdde4ceec--bat-signal-batman-logo](https://user-images.githubusercontent.com/387249/30454559-996620de-9951-11e7-93e4-8e41d27b48f9.jpg)

@tarekziade @davehunt HALP!

Version 1.8 fails to retrieve the project repo from the Service Book API endpoint, and instead receives a 404 after issuing its GET:

```
Testing project kinto
[Pipeline] httpRequest
HttpMethod: GET
URL: https://servicebook.stage.mozaws.net/api/project
Sending request to url: https://servicebook.stage.mozaws.net/api/project
Response Code: HTTP/1.1 404 NOT FOUND
[Pipeline] End of Pipeline
```

I suspect that it's because we might not be issuing the POSTs nor PUTs which we were in 1.7 (nor, it appears, sending content-type: application/json).

Working: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/kinto.integration.stage/35/console
Failing: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/kinto.integration.stage/28/console

More as I have it!

Full output here: https://gist.github.com/stephendonner/83e577e1f7ba420248579545f40ee25e

**Comment by tarekziade** [comment]
The right API endpoint is https://servicebook-api.stage.mozaws.net/api/project
