### ISSUE TITLE
Named attributes help

### ISSUE THREAD

**Issue by michaelpporter** [mozilla/fxtest-jenkins-pipeline#37]
In the readme you suggest we can call a custom library using the named attributes:

```groovy
// specify all values
ircNotification(
  channel: '#fx-test-alerts',
  nick: 'fxtest',
  server: 'irc.mozilla.org:6697'
)
```

```groovy
slackNotify(
  message: 'custom message testing',
  channel: '#jenkinst-test',
  color: 'danger'
)
```

When I try the example I get an error but it works when I remove the names:

```bash
hudson.remoting.ProxyException: groovy.lang.MissingMethodException: No signature of method: slackNotify.call() is applicable for argument types: (java.util.LinkedHashMap) values: [[message:custom message testing, channel:#jenkins-test, color:danger]]
```

```groovy
slackNotify(
  'custom message testing',
  '#jenkinst-test',
  'danger'
)
```

Is there a plugin or trick to get the names to work?

**Comment by davehunt** [comment]
Hi @michaelpporter! I think this is related to [JENKINS-43246](https://issues.jenkins-ci.org/browse/JENKINS-43246). If you'd like to improve our readme, I would gladly merge any suggestions.

**Comment by michaelpporter** [comment]
Thank you for the information on the issue. As far as the offer to help cleanup the readme; if it is still and issue after the first of the year I will be glad to help. Work is in our busy season so I do not have extra time at the moment.

**Comment by michaelpporter** [comment]
The desire is there, the time is not. I hope the issue gets resolved so named attributes will be supported. All I would do is remove the names from the readme, which I feel is bypassing the real issue.
